### PR TITLE
app-emulation/sabayon-lxd-imagebuilder: Bump v.0.1.0

### PR DESCRIPTION
**Pull request by geaaru**
Package-Manager: Portage-2.3.11, Repoman-2.3.3
RepoMan-Options: --force (currently ebuild app-emulation/lxd not support ~arm/~arm64)

### CODE REVIEW

**Comment by mudler** [comment]
While we could also merge that, it won't work on Gentoo upstream. You can also drop those keywords from ebuild and unmask them on the client/builder when you need them

**Comment by mudler** [comment]
Also, specify a workdir and have some gain 👍

**Comment by geaaru** [comment]
Hi,
for gentoo upstream I will add it in the near future, I have already an open pull request in waiting I don't want "too much meat to the fire"... about your suggestion to workdir do you said a directory where create tarballs or something related to ebuild ?

**Comment by mudler** [comment]
Ok then, we will round the edges later.. 😄

**Pull request merged**
