### PR TITLE
Bumping Atom to 1.4.0, bumping Moksha to 0.2.0

### PR DESCRIPTION
**Pull request by fusion809**

### CODE REVIEW

**Comment by mudler** [comment]
what's that? https://github.com/fusion809/for-gentoo/commit/343ac0719ffb6e658fc0d759264e9110d7ffe617
The other pull request seems fine, i don't see the reason for this one

**Comment by fusion809** [comment]
This one includes a bump for x11-wm/moksha too, to version 0.2.0.

**Comment by mudler** [comment]
https://github.com/fusion809/for-gentoo/commit/343ac0719ffb6e658fc0d759264e9110d7ffe617 -> Sorry, we could not display the entire diff because too many files (1,967) changed.

**Comment by fusion809** [comment]
The Atom ebuild I have tested, successfully. The Moksha one, well as I have previously told ya I couldn't build the Moksha 0.1.0 ebuild because of access violation errors that occurred, even though the Entropy build server were able to build this ebuild without issue. So I did not try to build this ebuild.

**Comment by mudler** [comment]
I'm going to close this pull request in favour of #52. The first commit almost include all packages in the repo, check it out yourself.

**Pull request closed without merging**
