### PR TITLE
Fix themes SRC_URI

### PR DESCRIPTION
**Pull request by geaaru**

### CODE REVIEW

**Comment by Enlik** [comment]
Looks fine, but can you change to use the usual Sabayon convention in commit messages?

**Comment by geaaru** [comment]
Hi, commit message of pull request title or for commit?
For commit I used classic [package] Description like for gentoo tree (but without repoman).
What is usual Sabayon convention ?

**Comment by Enlik** [comment]
Ah, right. My mistake.

**Comment by Enlik** [comment]
thanks :)

**Pull request merged**
